// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpskukvdzlurrbqlgtuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc2t1a3Zkemx1cnJicWxndHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjY4ODcsImV4cCI6MjA3MDg0Mjg4N30.g0AcsB-0_uY55uoJz5zvkegC86PnAYxTPuUJy9MkID4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});